name: 'Bump version and publish'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bump-version:
    name: Bump version and publish
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: cat package.json
        run: cat ./package.json

      - name: Version Bump
        id: version-bump
        uses: phips28/gh-action-bump-version@master
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

      - name: cat package.json
        run: cat ./package.json

      - name: Login to registry
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@i-want-to-help-ukraine'

      - name: npm install
        run: npm install

      - name: npm publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.PACKAGES_TOKEN}}

      - name: Output Step
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
